### ISSUE TITLE
Missing ')' backet on SHA3

### ISSUE THREAD

**Issue by Bart-Janssen** [MiragePV/OptimizedJCAlgs#4]
I can confirm SHA3 works as expect, however while compiling there is a missing ')' bracked in file: Sha3/src/Sha3.java on line 125:
rotl[8] = (byte)(rotl[0]; should be rotl[8] = (byte)(rotl[0]);

**Comment by petrs** [comment]
Thank you @Bart-Janssen for the reporting, this is indeed a mistake, I opened PR https://github.com/MiragePV/OptimizedJCAlgs/pull/5 for @MiragePV to merge
